[package]
name = "baiken"
version = "0.17.0"
edition = "2021"
authors = ["yakiimoninja"]
repository = "https://github.com/yakiimoninja/baiken"
description = "A Discord bot that displays Guilty Gear Strive frame data."
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.7"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
serde = "1.0.193"
dotenv = "0.15"
ureq = { version = "2.9.0", features = ["charset"] }
md-5 = "0.10.6"
rand = "0.8.5"
colored = "2.0.4"
# Uncomment for debugging
# tracing = "0.1.29"
# tracing-subscriber = "0.3.3"
